openapi: 3.0.3
info:
  title: Fixed Deposits API (Superseded)
  version: 2.0.0
  description: |
    This contract is superseded.

    Fixed deposits are no longer managed through a standalone `/api/fixed-deposits` API.
    They are now modeled as `BankAccount` resources with `accountType = FixedDeposit`
    under the existing `/api/bank-accounts` endpoints.

    Use the BankAccount API for create/read/update/delete operations.

tags:
  - name: Superseded
    description: Reference note for deprecated standalone fixed-deposit API

paths: {}

components:
  schemas:
    FixedDepositViaBankAccount:
      type: object
      description: BankAccount fields relevant when accountType is FixedDeposit
      required:
        - accountType
        - bankName
        - totalAssets
        - interestRate
        - currency
        - termMonths
        - startDate
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        accountType:
          type: string
          enum: [Savings, FixedDeposit]
          example: FixedDeposit
        bankName:
          type: string
          maxLength: 100
        totalAssets:
          type: number
          format: decimal
          description: Principal amount for fixed deposits
        interestRate:
          type: number
          format: decimal
          description: Annual interest rate (%)
        currency:
          type: string
          minLength: 3
          maxLength: 3
          example: TWD
        termMonths:
          type: integer
          minimum: 1
        startDate:
          type: string
          format: date-time
        maturityDate:
          type: string
          format: date-time
          nullable: true
        expectedInterest:
          type: number
          format: decimal
          nullable: true
        actualInterest:
          type: number
          format: decimal
          nullable: true
        fixedDepositStatus:
          type: string
          enum: [Active, Matured, Closed, EarlyWithdrawal]
          nullable: true
        note:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

x-superseded:
  replacedBy: /api/bank-accounts
  migrationGuidance:
    - Set `accountType` to `FixedDeposit` when creating fixed deposits.
    - Use `totalAssets` as principal amount.
    - Provide `termMonths` and `startDate` for fixed-deposit schedule calculation.
    - Read `maturityDate`, `expectedInterest`, and `fixedDepositStatus` from bank-account responses.
