openapi: 3.0.3
info:
  title: Installments API
  version: 2.1.0
  description: |
    API for managing credit card installment purchases.

    Notes:
    - Installments support create, read, delete, and upcoming-payment preview.
    - Editing (`PUT`) and manual payment recording endpoints were removed.
    - Remaining installments are auto-calculated from current date, `firstPaymentDate`,
      and credit card `paymentDueDay`.

paths:
  /api/credit-cards/{creditCardId}/installments:
    get:
      summary: Get all installments for a credit card
      operationId: getInstallments
      tags: [Installments]
      parameters:
        - name: creditCardId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [Active, Completed, Cancelled]
          description: Filter by status
      responses:
        '200':
          description: List of installments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InstallmentResponse'
        '401':
          description: Unauthorized
        '404':
          description: Credit card not found

    post:
      summary: Create a new installment purchase
      operationId: createInstallment
      tags: [Installments]
      parameters:
        - name: creditCardId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInstallmentRequest'
      responses:
        '201':
          description: Installment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallmentResponse'
        '400':
          description: Validation error
        '404':
          description: Credit card not found

  /api/installments:
    get:
      summary: Get all installments for current user (across all cards)
      operationId: getAllInstallments
      tags: [Installments]
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [Active, Completed, Cancelled]
      responses:
        '200':
          description: List of all installments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InstallmentResponse'

  /api/installments/{id}:
    get:
      summary: Get an installment by ID
      operationId: getInstallment
      tags: [Installments]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Installment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallmentResponse'
        '404':
          description: Not found
        '403':
          description: Access denied

    delete:
      summary: Delete an installment
      operationId: deleteInstallment
      tags: [Installments]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Installment deleted
        '404':
          description: Not found
        '403':
          description: Access denied

  /api/installments/upcoming:
    get:
      summary: Get upcoming installment payments for next N months
      operationId: getUpcomingPayments
      tags: [Installments]
      parameters:
        - name: months
          in: query
          required: false
          schema:
            type: integer
            default: 3
            minimum: 1
            maximum: 12
      responses:
        '200':
          description: Upcoming payments by month
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpcomingPaymentsResponse'

components:
  schemas:
    InstallmentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        creditCardId:
          type: string
          format: uuid
        creditCardName:
          type: string
          description: Card name for display
        description:
          type: string
        totalAmount:
          type: number
          format: decimal
        numberOfInstallments:
          type: integer
        remainingInstallments:
          type: integer
          description: Auto-calculated from current date and payment due day
        monthlyPayment:
          type: number
          format: decimal
        unpaidBalance:
          type: number
          format: decimal
          description: monthlyPayment × remainingInstallments (dynamic)
        paidAmount:
          type: number
          format: decimal
        progressPercentage:
          type: number
          format: decimal
        firstPaymentDate:
          type: string
          format: date-time
        status:
          type: string
          enum: [Active, Completed, Cancelled]
          description: Effective status derived from dynamic remaining count
        note:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateInstallmentRequest:
      type: object
      required:
        - description
        - totalAmount
        - numberOfInstallments
        - firstPaymentDate
      properties:
        description:
          type: string
          maxLength: 200
        totalAmount:
          type: number
          format: decimal
          minimum: 0
          exclusiveMinimum: true
        numberOfInstallments:
          type: integer
          minimum: 2
        firstPaymentDate:
          type: string
          pattern: '^\\d{4}-\\d{2}$'
          description: |
            First payment month in YYYY-MM format (from month picker intent).
            Backend aligns the day-of-month to credit card `paymentDueDay`.
        note:
          type: string
          maxLength: 500

    UpcomingPaymentsResponse:
      type: object
      properties:
        months:
          type: array
          items:
            type: object
            properties:
              month:
                type: string
                format: date
                description: First day of month
              totalPayment:
                type: number
                format: decimal
              installments:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    description:
                      type: string
                    creditCardName:
                      type: string
                    monthlyPayment:
                      type: number
                      format: decimal

x-removed-endpoints:
  - path: /api/installments/{id}
    method: put
    reason: Installment editing removed
  - path: /api/installments/{id}/record-payment
    method: post
    reason: Manual payment recording removed
  - path: /api/installments/{id}/payoff
    method: post
    reason: Manual payoff flow removed from current contract
