openapi: 3.0.3
info:
  title: Installments API
  version: 1.0.0
  description: API for managing credit card installment purchases

paths:
  /api/credit-cards/{creditCardId}/installments:
    get:
      summary: Get all installments for a credit card
      operationId: getInstallments
      tags: [Installments]
      parameters:
        - name: creditCardId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [Active, Completed, Cancelled]
          description: Filter by status
      responses:
        '200':
          description: List of installments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InstallmentResponse'
        '401':
          description: Unauthorized
        '404':
          description: Credit card not found

    post:
      summary: Create a new installment purchase
      operationId: createInstallment
      tags: [Installments]
      parameters:
        - name: creditCardId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInstallmentRequest'
      responses:
        '201':
          description: Installment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallmentResponse'
        '400':
          description: Validation error
        '404':
          description: Credit card not found

  /api/installments:
    get:
      summary: Get all installments for current user (across all cards)
      operationId: getAllInstallments
      tags: [Installments]
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [Active, Completed, Cancelled]
      responses:
        '200':
          description: List of all installments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InstallmentResponse'

  /api/installments/{id}:
    get:
      summary: Get an installment by ID
      operationId: getInstallment
      tags: [Installments]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Installment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallmentResponse'
        '404':
          description: Not found
        '403':
          description: Access denied

    put:
      summary: Update an installment
      operationId: updateInstallment
      tags: [Installments]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateInstallmentRequest'
      responses:
        '200':
          description: Installment updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallmentResponse'
        '400':
          description: Validation error
        '404':
          description: Not found

  /api/installments/{id}/record-payment:
    post:
      summary: Record a monthly payment
      operationId: recordInstallmentPayment
      tags: [Installments]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordPaymentRequest'
      responses:
        '200':
          description: Payment recorded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallmentResponse'
        '400':
          description: No remaining installments
        '404':
          description: Not found

  /api/installments/{id}/payoff:
    post:
      summary: Early payoff - mark installment as completed
      operationId: payoffInstallment
      tags: [Installments]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Installment paid off
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallmentResponse'
        '400':
          description: Already completed
        '404':
          description: Not found

  /api/installments/upcoming:
    get:
      summary: Get upcoming installment payments for next N months
      operationId: getUpcomingPayments
      tags: [Installments]
      parameters:
        - name: months
          in: query
          required: false
          schema:
            type: integer
            default: 3
            minimum: 1
            maximum: 12
      responses:
        '200':
          description: Upcoming payments by month
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpcomingPaymentsResponse'

components:
  schemas:
    InstallmentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        creditCardId:
          type: string
          format: uuid
        creditCardName:
          type: string
          description: Card name for display
        description:
          type: string
        totalAmount:
          type: number
          format: decimal
        numberOfInstallments:
          type: integer
        remainingInstallments:
          type: integer
        monthlyPayment:
          type: number
          format: decimal
        unpaidBalance:
          type: number
          format: decimal
          description: monthlyPayment × remainingInstallments
        paidAmount:
          type: number
          format: decimal
        progressPercentage:
          type: number
          format: decimal
        startDate:
          type: string
          format: date
        status:
          type: string
          enum: [Active, Completed, Cancelled]
        note:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateInstallmentRequest:
      type: object
      required:
        - description
        - totalAmount
        - numberOfInstallments
        - startDate
      properties:
        description:
          type: string
          maxLength: 200
        totalAmount:
          type: number
          format: decimal
          minimum: 0
          exclusiveMinimum: true
        numberOfInstallments:
          type: integer
          minimum: 2
        startDate:
          type: string
          format: date
        note:
          type: string
          maxLength: 500

    UpdateInstallmentRequest:
      type: object
      properties:
        description:
          type: string
          maxLength: 200
        note:
          type: string
          maxLength: 500

    RecordPaymentRequest:
      type: object
      properties:
        numberOfPayments:
          type: integer
          minimum: 1
          default: 1
          description: Number of payments to record (default 1)

    UpcomingPaymentsResponse:
      type: object
      properties:
        months:
          type: array
          items:
            type: object
            properties:
              month:
                type: string
                format: date
                description: First day of month
              totalPayment:
                type: number
                format: decimal
              installments:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    description:
                      type: string
                    creditCardName:
                      type: string
                    monthlyPayment:
                      type: number
                      format: decimal
